version: "3.8"
services:
  vprodb:
    build:
      context: ./Docker-files/db
    image: hibhad/vprofiledb
    container_name: vprodb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass
  vprocache01:
    image: memcached
    ports:
      - "11211:11211"

  vpromq01:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  vproapp:
    build:
      context: ./Docker-files/app

    image: hibhad/vprofileapp
    container_name: vproapp
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webappa

  vproweb:
    build:
      context: ./Docker-files/web
    image: hibhad/vprofileweb
    container_name: vproweb
    restart: always
    ports:
      - "80:80"

volumes:
  vprodbdata: {}
  vproappdata: {}
